### ISSUE TITLE
Биті посилання на задачі

### ISSUE THREAD

**Issue by vladgolubev** [pigovsky/contest#1]
У файлі README.md посилання ведуть на стоорінку з помилкою

* https://www.codingame.com/ide/3066498205887824e23304f9ba3dbee39f9bf0a
* https://www.codingame.com/ide/3057942913f829fb8b6d52bafbc74f2dae20892

**Comment by pigovsky** [comment]
Please fix these links and create a pull request

**Comment by tyran-sergiy** [comment]
#10

**Comment by pigovsky** [comment]
thanks!
